# Generated by Django 3.0.8 on 2020-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vue_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
    ]
