# Generated by Django 3.0.8 on 2020-07-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vue_App', '0003_auto_20200723_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='CompletedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='DeletedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
